plugin.version=${pluginVersion}
release.build=${releaseBuild}
java.target=${javaTarget}
paper.target=${paperTarget}
paper.api=${paperApiVersion}
paper.channel=${paperChannel}
artifact.filename=${artifactFileName}
