name: PlotMarkers
main: com.bobcat00.plotmarkers.PlotMarkers
version: ${version}
author: Bobcat00
api-version: '26.2'
depend: [BlueMap,PlotSquared]
softdepend: ['Multiverse-Core']
commands:
  plotmarkers:
    description: Shows PlotMarkers information and documentation.
    usage: /plotmarkers info
