name: PlotMarkers
main: com.bobcat00.plotmarkers.PlotMarkers
version: ${pluginVersion}
author: Bobcat00
api-version: '${paperTarget}'
depend: [BlueMap,PlotSquared]
softdepend: ['Multiverse-Core']
commands:
  plotmarkers:
    description: Shows PlotMarkers information, status, version, and diagnostics.
    usage: /plotmarkers [info|version|status|debug]
